version: "3"
services:
  web:
    env_file:
      - docker.env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/app
    depends_on:
      - db
    command: ["./wait-for", "db:5432", "--", "yarn", "docker:dev"]
  db:
    image: postgres:12.1-alpine
    ports:
      - "5431:5432"
    env_file:
      - docker.env
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
