apiVersion: v2
name: xui-terms-and-conditions
home: https://github.com/hmcts/rpx-xui-terms-and-conditions
version: 0.2.2
description: Terms and Conditions
maintainers:
  - name: HMCTS RPX XUI
dependencies:
  - name: nodejs
    version: 2.3.4
    repository: '@hmctspublic'
  - name: postgresql
    version: ~8.9.8
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
keywords:
- nodejs
- postgres
- postgresql
