dependencies:
  - name: nodejs
    version: 2.3.4
    repository: '@hmctspublic'
  - name: postgresql
    version: ~8.9.8
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
