nodejs:
  applicationPort: 3000
  memoryLimits: 1024Mi
  cpuLimits: 1000m
  environment:
    REFORM_TEAM: rpx
    REFORM_SERVICE_NAME: xui-terms-and-conditions
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    XUI_ENV: production
    S2S_SECRET: ${S2S_SECRET}
    IDAM_SECRET: ${IDAM_SECRET}
    POSTGRE_SERVER_PORT: 5432
    POSTGRE_DB_NAME: xui_tc
  keyVaults:
    rpx:
      resourceGroup: rpx
      secrets:
        - mc-s2s-client-secret
        - mc-idam-client-secret
        - AppInsightsInstrumentationKey
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

## Postgres chart configuration
## https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml

postgresql:
  ## Whether to deploy the Postgres Chart or not
  enabled: true
  ## Disable Postgres Persistence
  persistence:
    enabled: false
  ## Default Postgres Configuration parameters
  postgresqlUsername: xuipostgres
  postgresqlPassword: xuipassword
  postgresqlDatabase: xuidatabase