nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
       S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
       NODE_TLS_REJECT_UNAUTHORIZED: '0'
       S2S_SECRET: ${S2S_SECRET}
       IDAM_SECRET: ${IDAM_SECRET}
       NODE_ENV: preview
       XUI_ENV: preview
       POSTGRE_SERVER_NAME: "{{ .Release.Name }}-postgresql"
       POSTGRE_USERNAME: xui_tc
       POSTGRE_USER_PW: xui_tc
       POSTGRE_DB_NAME: xui_tc
postgresql:
  enabled: true
  postgresqlUsername: xui_tc
  postgresqlPassword: xui_tc
  postgresqlDatabase: xui_tc
  environment:
      POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
      POSTGRES_NAME: xui_tc
      POSTGRES_USERNAME: xui_tc
      POSTGRES_PASSWORD: xui_tc
      POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"
