nodejs:
  aadIdentityName:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
       NODE_TLS_REJECT_UNAUTHORIZED: '0'
       XUI_ENV: preview
       POSTGRES_SERVER_NAME: "{{ .Release.Name }}-postgresql"
       POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
       POSTGRES_PW: "{{ .Values.postgresql.postgresqlPassword }}"
       POSTGRES_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  keyVaults:
    rpx:
      secrets:
        - mc-s2s-client-secret
postgresql:
  enabled: true
  postgresqlUsername: xui_tc
  postgresqlPassword: xui_tc
  postgresqlDatabase: xui_tc
  persistence:
    enabled: false
