nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    NODE_CONFIG_ENV: aat
    NODE_TLS_REJECT_UNAUTHORIZED: '1'
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}