nodejs:
  aadIdentityName:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  #
  # We need to specify {{ .Release.Name }}-postgresql here
  # as the build does not work if we specify it within preview.yaml
  #
  environment:
       NODE_TLS_REJECT_UNAUTHORIZED: '0'
       XUI_ENV: preview
       POSTGRES_SERVER_NAME: "{{ .Release.Name }}-postgresql"
       POSTGRES_USERNAME: "xui_tc"
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB_NAME: "xui_tc"
       POSTGRES_SSL: false
       #
       # In the Preview environment the Postgres Database password is 'xui_tc'
       # therefore we should not use the secrets.rpx.postgresql-admin-pw
       # password.
       #
       # The secrets.rpx.postgresql-admin-pw is available on the Preview environment
       # and is the same as the AAT secret, but due to the fact that this is a public repo
       # we do not want to check in the AAT secret in this file. Therefore we have
       # this POSTGRES_USE_KEYVAULT_SECRET flag.
       #
       POSTGRES_USE_KEYVAULT_SECRET: false
postgresql:
  enabled: true
  postgresqlUsername: xui_tc
  postgresqlPassword: ${POSTGRES_PASSWORD}
  postgresqlDatabase: xui_tc
  persistence:
    enabled: false
