nodejs:
  aadIdentityName:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
       NODE_TLS_REJECT_UNAUTHORIZED: '0'
       XUI_ENV: preview
       POSTGRES_SERVER_NAME: "{{ .Release.Name }}-postgresql"
       POSTGRES_USERNAME: "xui_tc"
       POSTGRES_PASSWORD: "xui_tc"
       POSTGRES_DB_NAME: "xui_tc"
postgresql:
  enabled: true
  postgresqlUsername: xui_tc
  postgresqlPassword: xui_tc
  postgresqlDatabase: xui_tc
  persistence:
    enabled: false
  initdbScripts:
    init.sql: |-
      CREATE TABLE IF NOT EXISTS "TCDocument"
      (
          id             serial PRIMARY KEY,
          document       TEXT,
          "mimeType"     VARCHAR(80) NOT NULL DEFAULT 'text/html',
          "creationDate" TIMESTAMP   NOT NULL DEFAULT NOW(),
          version        serial      NOT NULL UNIQUE
      );
      CREATE TABLE IF NOT EXISTS "TCApp"
      (
          id           serial PRIMARY KEY,
          app          varchar(50) NOT NULL UNIQUE
      );
      CREATE TABLE IF NOT EXISTS "TCDocumentApp"
      (
          id           serial PRIMARY KEY,
          "documentId" INTEGER REFERENCES "TCDocument" (id) ON DELETE RESTRICT,
          "appId" INTEGER REFERENCES "TCApp" (id) ON DELETE RESTRICT
      );
      CREATE TABLE IF NOT EXISTS "TCUserAgreement"
      (
          id              serial PRIMARY KEY,
          "userId"        UUID      NOT NULL,
          "documentAppId" INTEGER REFERENCES "TCDocumentApp" (id) ON DELETE RESTRICT,
          "agreementDate" TIMESTAMP NOT NULL DEFAULT NOW()
      );
      insert into "TCApp"("app") values('xuiwebapp'),('xuimowebapp') ON CONFLICT DO NOTHING;
      insert into "TCDocument" (id, document, "mimeType") values(1, '<h1>Paddy Power - Do you accept?</h1>', 'text/html') ON CONFLICT DO NOTHING;
      insert into "TCDocumentApp" ("documentId", "appId")
      select 1, "id" from "TCApp";
