apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hmcts.releaseName" . }}
  labels:
    {{- ( include "labels" . ) | indent 4 }}
  annotations:
    {{- ( include "annotations" . ) | indent 4 }}
