swagger: "2.0"
info:
  version: 1.0.0
  title: terms-and-conditions
  description: Terms and Conditions
basePath: /api/v1
tags:
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:

  UsersBody:
    type: array
    title: users
    items:
      type: object
      properties:
        userId:
          type: string
          example: jo

  CopyBody:
    type: object
    title: copy
    required:
      - content
    properties:
      content:
        type: string
        example: no_stress

paths:

  /termsAndConditions/{app}/users/{version}:
    get:
      tags:
        - Users routes
      description: Get all Users who have accepted a specific version of Terms & Conditions.
      parameters:
        - name: app
          in: path
          required: true
          description: The application identifier
          type: string
        - name: version
          in: path
          required: true
          description: Terms and Conditions version number
          type: number
      responses:
        200:
          description: Returns an array of Users who have accepted a specific version of Terms & Conditions.
    post:
      tags:
        - Users routes
      description: Add Users who have accepted the Terms and Conditions.
      parameters:
        - name: app
          in: path
          description: Create new users
          required: true
          type: string
        - name: version
          in: path
          required: true
          description: Terms and Conditions version number
          type: number
        - name: users
          in: body
          description: users
          required: true
          schema:
            $ref: "#/definitions/UsersBody"
      responses:
        200:
          description: Signals success of adding the Users to the datastore

  /termsAndConditions/{app}/users/{userId}/{version}:
    get:
      tags:
        - Users routes
      parameters:
        - name: app
          in: path
          required: true
          description: The application identifier
          type: string
        - name: version
          in: path
          required: true
          description: Terms and Conditions version number
          type: number
        - name: userId
          in: path
          required: true
          description: User id
          type: string
      responses:
        200:
          description: Return 200 Success if the User has accepted the version of Terms and Conditions.
        404:
          description: Returns 404 if no User has been found.

  /termsAndConditions:
    get:
      tags:
        - termsAndConditions
      description: Fetch all copies
      responses:
        200:
          description: Returns all copies
    post:
      tags:
        - termsAndConditions
      description: Create a new copy
      parameters:
        - name: content
          in: body
          description: a copy
          required: true
          schema:
            $ref: "#/definitions/CopyBody"
      responses:
        200:
          description: Returns all copies

  /termsAndConditions/{version}:
    get:
      tags:
        - termsAndConditions
      parameters:
        - name: version
          in: path
          required: true
          description: The version of the copy to retrieve
          type: integer
      responses:
        200:
          description: Returns the copy with the specified version
        404:
          description: Copy not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
