environment: 'aat'
database:
  name: POSTGRES_DB_NAME
  host: POSTGRES_SERVER_NAME
  username: POSTGRES_USERNAME
  port: POSTGRES_SERVER_PORT
  ssl: POSTGRES_SSL
  password: POSTGRES_PASSWORD
# Do not have secrets.rpx.postgresql-admin-pw or
# secrets.rpx.appinsights-instrumentationkey-tc
# defined here, as it will overwrite secrets.rpx.postgresql-admin-pw
# contained within the .yaml file.
proxy:
  host: PROXY_HOST
  port: PROXY_PORT
client:
  whitelist: CLIENT_WHITELIST
services:
  s2s: S2S_TOKEN_URL
  idam:
    api-url: IDAM_SERVICE_URL

