#
# preview .yaml
#
# This file preview.yaml is used by the Preview environment. ( Jenkins Deploy )
#
# It's VALUES ie. 'POSTGRES_SERVER_PORT' are set by the files in charts/xui-terms-and-conditions.
#
# Please be aware that within charts/xui-terms-and-conditions there is a hierarchical way
# in which the .yaml are used.
#
# @see charts/xui-terms-and-conditions
#
# NB: do not have `secrets.rpx.postgresql-admin-pw` or `secrets.rpx.appinsights-instrumentationkey-tc`
# defined in this file as it will override the secret references in the values.yaml file.
#
environment: 'preview'
database:
  name: "xui_tc"
  host: "{{ .Release.Name }}-postgresql"
  username: "xui_tc"
  port: POSTGRES_SERVER_PORT
  ssl: false
  password: "xui_tc"
proxy:
  host: PROXY_HOST
  port: PROXY_PORT
client:
  whitelist: CLIENT_WHITELIST
services:
  s2s: S2S_TOKEN_URL
  idam:
    api-url: IDAM_SERVICE_URL
